version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8080
